In [1]:
import numpy as np
import tensorflow as tf

In [2]:
np_array=tf.constant(np.array([1,2,3,4]))
np_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [3]:
t_1d=tf.constant([[1,2,3],[3,4,5]])
t_1d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [4]:
np_2d_1=tf.constant([1,2,3,4],shape=(2,2))
np_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [5]:
np_2d_1=tf.constant([1,2,3,4],shape=(2,2),dtype="int64")
np_2d_1

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [6]:
np_2d_1=tf.constant([1,2,3,4],shape=(2,2),dtype="float32")
np_2d_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [7]:
np_3d_1=tf.constant([[[1,2],[3,4],[5,6]]],dtype="float32")
np_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float32)>

In [8]:
# type of constant
type(np_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [9]:
# shape of constant
np_3d_1.shape

TensorShape([1, 3, 2])

In [10]:
#access constant value
t_1d.numpy()

array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)

In [11]:
# c0onstant datatype
t_1d.dtype

tf.int32

In [ ]:
# ham tensor flow conastant me mix value nahi de sakte ,
# agar hum esme mix value dete h to vo hame error dega
# tf.constant([1,23.2,"hello"])