In [2]:
import numpy as np
import tensorflow as tf

In [4]:
np_array=tf.constant(np.array([1,2,3,4]))
np_array

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [5]:
t_1d=tf.constant([[1,2,3],[3,4,5]])
t_1d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]])>

In [6]:
np_2d_1=tf.constant([1,2,3,4],shape=(2,2))
np_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [9]:
np_2d_1=tf.constant([1,2,3,4],shape=(2,2),dtype="int64")
np_2d_1

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]], dtype=int64)>

In [10]:
np_2d_1=tf.constant([1,2,3,4],shape=(2,2),dtype="float32")
np_2d_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [12]:
np_3d_1=tf.constant([[[1,2],[3,4],[5,6]]],dtype="float32")
np_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float32)>