In [2]:
#variable: variables allows us to add new trainable parammeter to graph
# tf.variable()

In [3]:
import tensorflow as tf

In [4]:
#create tensor
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [5]:
a=tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [6]:
a.name

'Variable:0'

In [7]:
a.shape

TensorShape([4])

In [8]:
a.dtype

tf.int32

In [9]:
a.numpy()

array([1, 2, 3, 4], dtype=int32)

In [10]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [11]:
# Create TF using Integer , Float , String , Bool , Complex Number
t_f=tf.Variable([1.2,4.4,5,6])
t_f

# Create tr using constant tensorflow variable


<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 4.4, 5. , 6. ], dtype=float32)>

In [12]:
t_s=tf.Variable(['a','b','c','d'])
t_s

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [13]:
t_f=tf.Variable([True,False])
t_f

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [14]:
# python me jab ham complex number banate h to 'i' ki jagah per 'j'  ka use karte h
t_cx=tf.Variable([3+4j])
t_cx

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

In [15]:
# Create TF from Constant TensorFlow Variable

In [16]:
t_con=tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [17]:
t_v=tf.Variable(t_con)
t_v

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [19]:
#create tf variable with different shape
t_2d=tf.Variable([[2,3],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [20]:
t_2d=tf.Variable([[2,3],[4,5]],shape=(2,2) , dtype='float32')
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [23]:
#reshape variable
a=tf.reshape(a,(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [24]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [25]:
# Get index of highest value

t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [26]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [27]:
tf.argmax(t_2d).numpy()

array([1, 1])

In [ ]:
# Viewed/ Convert as a tensor



a=tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [32]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [33]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [34]:
# Change and assign new value to tensor

a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
a.assign([3,4,5,6]) # yaha per hamarea data replace hota h

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([3, 4, 5, 6], dtype=int32)>

In [36]:
# Assign variable with another memory


a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([3, 4, 5, 6], dtype=int32)>

In [37]:
a.assign_add([4,5,6,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 7,  9, 11, 13], dtype=int32)>

In [39]:
a.assign_sub([1,2,3,4])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([6, 7, 8, 9], dtype=int32)>

In [41]:
#Can't change the shape


# a.assign([2,3,4,5,2])

In [44]:
#Can't change the type


# a.assign([2.1,3.3,4.5,5.1,2.5])